# Generated by Django 5.0 on 2023-12-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/committee_members/')),
            ],
        ),
    ]
