# Generated by Django 5.0 on 2023-12-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Committee_Member',
            new_name='Member',
        ),
    ]
