# Generated by Django 5.0 on 2023-12-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0002_rename_committee_member_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['id']},
        ),
    ]
