# Generated by Django 5.0 on 2023-12-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0003_alter_member_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='', upload_to='images/committee_members/'),
        ),
    ]
