# Generated by Django 5.0 on 2023-12-06 19:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0004_alter_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/committee_members/'),
        ),
    ]
