# Generated by Django 5.0 on 2023-12-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0005_alter_member_id_alter_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, height_field='400', null=True, upload_to='images/committee_members/', width_field='400'),
        ),
    ]
