# Generated by Django 4.2.8 on 2023-12-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0008_alter_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
