# Generated by Django 4.2.8 on 2023-12-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0009_member_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='image',
        ),
        migrations.AlterField(
            model_name='member',
            name='image_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
