# Generated by Django 4.2.8 on 2023-12-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0010_remove_member_image_alter_member_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='batch',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='image_link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(max_length=30),
        ),
    ]
