# Generated by Django 4.2.8 on 2023-12-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0011_alter_member_batch_alter_member_image_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='sno',
            field=models.IntegerField(default=0, verbose_name='S.No'),
        ),
    ]
