# Generated by Django 4.2.8 on 2023-12-09 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0012_member_sno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['sno']},
        ),
        migrations.AlterField(
            model_name='member',
            name='sno',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=25)], verbose_name='S.No'),
        ),
    ]
