# Generated by Django 4.2.8 on 2024-04-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0013_alter_member_options_alter_member_sno'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='committee_members/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image_link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Photo Link'),
        ),
    ]
