# Generated by Django 4.2.8 on 2024-07-26 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0014_member_image_alter_member_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='image_link',
        ),
        migrations.AlterField(
            model_name='member',
            name='sno',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=25)], verbose_name='S.No.'),
        ),
    ]
