# Generated by Django 4.2.8 on 2024-07-26 20:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0015_remove_member_image_link_alter_member_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
