# Generated by Django 4.2.8 on 2024-07-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0017_alter_member_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='committee_members/'),
        ),
    ]
