# Generated by Django 4.2.8 on 2024-07-26 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0018_member_image_public_id_alter_member_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='image_public_id',
        ),
    ]
