# Generated by Django 4.2.8 on 2024-07-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0019_remove_member_image_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image_link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Photo Link'),
        ),
    ]
