# Generated by Django 4.2.8 on 2024-09-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0020_member_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='image_link',
        ),
    ]
