# Generated by Django 4.2.8 on 2023-12-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('url', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
