# Generated by Django 4.2.8 on 2025-10-26 07:39

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photolink",
            options={
                "ordering": ["-date"],
                "verbose_name": "Photo Link",
                "verbose_name_plural": "Photo Links",
            },
        ),
        migrations.AddField(
            model_name="photolink",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="photolink",
            name="is_visible",
            field=models.BooleanField(default=True, verbose_name="Is Visible"),
        ),
        migrations.AlterField(
            model_name="photolink",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="photolink",
            name="url",
            field=models.CharField(max_length=150, verbose_name="Link"),
        ),
    ]
